name: Daily Python Script

on:
  schedule:
    - cron: '0 10 * * *' # Runs at 00:10 UTC every day

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./src

      - name: Execute Python script
        run: python main.py
        working-directory: ./src
