
on:
 push:
    branches:
      - main
 schedule:
    - cron: "0 0 * * *"

jobs:
 Update_Wakatime_img:
    runs-on: ubuntu-latest # Specify the runner to use
    name: Update wakatime images
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" 
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
