
on:
 schedule:
    - cron: "0 0 * * *"

jobs:
 Update_Wakatime_img:
    runs-on: ubuntu-latest # Specify the runner to use
    name: Update wakatime images
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" 
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Set up Git
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git config -l
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update wakatime images"
          git push
        env:
          GH_TOKEN: ${{ github.token }}
